import {catchAsyncError} from "./catchAsyncError.js";
import ErrorHandler from "./error.js";
import jwt from "jsonwebtoken";
import {User} from "../models/userModel.js";

//middleware to protect the routes 

export const isAuthenticated= catchAsyncError(async (req,res,next) => {
    const {token} = req.cookies;   //getting the token from the cookies(destructing the token from the cookies)
    if(!token) {
        return next(new ErrorHandler("User is not autheticated", 400));
    }

    const decoded= jwt.verify(token,process.env.JWT_SECRET_KEY); //verifying the token that whether the token is generated by the server or not
    req.user= await User.findById(decoded.id); //finding the user by the id that is stored in the token

    next();
});